--------------------------------------------------------
--  파일이 생성됨 - 수요일-1월-27-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BNO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SEQ_BNO"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 261 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RNO
--------------------------------------------------------

   CREATE SEQUENCE  "XE"."SEQ_RNO"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_ATTACH
--------------------------------------------------------

  CREATE TABLE "XE"."TBL_ATTACH" 
   (	"SAVE_FILE_NAME" VARCHAR2(255 BYTE), 
	"REAL_FILE_NAME" VARCHAR2(255 BYTE), 
	"REG_DATE" DATE, 
	"BNO" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_BOARD
--------------------------------------------------------

  CREATE TABLE "XE"."TBL_BOARD" 
   (	"BNO" NUMBER(11,0), 
	"BOARD_TYPE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"WRITER" VARCHAR2(50 BYTE), 
	"VIEW_COUNT" NUMBER(11,0), 
	"REPLY_COUNT" NUMBER(11,0), 
	"REG_DATE" TIMESTAMP (6), 
	"UPDATE_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TBL_BOARD_TYPE
--------------------------------------------------------

  CREATE TABLE "XE"."TBL_BOARD_TYPE" 
   (	"BOARD_TYPE" VARCHAR2(45 BYTE), 
	"BOARD_NAME" VARCHAR2(45 BYTE), 
	"BOARD_SUN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "XE"."TBL_MEMBER" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_PW" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"POINT" NUMBER(11,0), 
	"ENABLED" NUMBER(1,0), 
	"LEVELS" VARCHAR2(50 BYTE), 
	"REG_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_REPLY
--------------------------------------------------------

  CREATE TABLE "XE"."TBL_REPLY" 
   (	"RNO" NUMBER(11,0), 
	"REPLY_TEXT" VARCHAR2(1000 BYTE), 
	"REPLYER" VARCHAR2(50 BYTE), 
	"REG_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"BNO" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into XE.TBL_ATTACH
SET DEFINE OFF;
REM INSERTING into XE.TBL_BOARD
SET DEFINE OFF;
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (201,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (202,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (203,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (204,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (205,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (206,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (207,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (208,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (209,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (210,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (211,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (212,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (213,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (214,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (215,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (216,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (217,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (218,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (219,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (220,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (221,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (222,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (223,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (224,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (225,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (226,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (227,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (228,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (229,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (230,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (231,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (232,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (233,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (234,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (235,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (236,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (237,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (238,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (239,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (240,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (241,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (242,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (243,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (244,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (245,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (246,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (247,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (248,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (249,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into XE.TBL_BOARD (BNO,BOARD_TYPE,TITLE,WRITER,VIEW_COUNT,REPLY_COUNT,REG_DATE,UPDATE_DATE) values (250,'notice','게시물테스트','관리자',null,null,to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('21/01/27 15:35:19.000000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into XE.TBL_BOARD_TYPE
SET DEFINE OFF;
REM INSERTING into XE.TBL_MEMBER
SET DEFINE OFF;
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_62','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_63','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_64','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_65','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_66','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_67','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_68','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_69','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_70','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_71','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_72','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_73','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_74','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_75','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_76','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_77','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_78','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_79','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_80','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_81','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_82','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_83','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_84','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_85','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_86','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_87','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_88','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_89','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_90','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_91','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_92','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_93','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_94','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_95','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_96','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_97','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_98','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_99','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('admin','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_ADMIN',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_1','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_2','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_3','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_4','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_5','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_6','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_7','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_8','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_9','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_10','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_11','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_12','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_13','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_14','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_15','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_16','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_17','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_18','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_19','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_20','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_21','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_22','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_23','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_24','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_25','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_26','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_27','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_28','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_29','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_30','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_31','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_32','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_33','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_34','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_35','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_36','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_37','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_38','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_39','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_40','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_41','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_42','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_43','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_44','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_45','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_46','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_47','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_48','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_49','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_50','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_51','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_52','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_53','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_54','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_55','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_56','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_57','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_58','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_59','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_60','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
Insert into XE.TBL_MEMBER (USER_ID,USER_PW,USER_NAME,EMAIL,POINT,ENABLED,LEVELS,REG_DATE,UPDATE_DATE) values ('user_61','$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO','관리자',null,null,1,'ROLE_USER',to_date('21/01/27','RR/MM/DD'),to_date('21/01/27','RR/MM/DD'));
REM INSERTING into XE.TBL_REPLY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TBL_ATTACH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."TBL_ATTACH_PK" ON "XE"."TBL_ATTACH" ("SAVE_FILE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."TBL_BOARD_PK" ON "XE"."TBL_BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_BOARD_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."TBL_BOARD_TYPE_PK" ON "XE"."TBL_BOARD_TYPE" ("BOARD_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."TBL_MEMBER_PK" ON "XE"."TBL_MEMBER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_REPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XE"."TBL_REPLY_PK" ON "XE"."TBL_REPLY" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure PROC_BOARD_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "XE"."PROC_BOARD_INSERT" 
(
  P_BOARD_TYPE IN VARCHAR2 
, P_COUNT IN NUMBER 
) AS 
BEGIN
  --실행방법: 쿼리에디터에서 CALL PROC_BOARD_INSERT('notice',50);
  FOR i IN 1..P_COUNT LOOP
        INSERT INTO TBL_BOARD
        (bno, board_type,title,content,writer,reg_date,update_date)
        VALUES
        (SEQ_BNO.nextval,P_BOARD_TYPE,'게시물테스트','게시물내용테스트','관리자',SYSDATE,SYSDATE);
      END LOOP;
    commit;
END PROC_BOARD_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure PROC_MEMBER_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "XE"."PROC_MEMBER_INSERT" 
(
  P_COUNT IN NUMBER 
, P_ROLE IN VARCHAR2 
) AS 
V_USER varchar2(20):='user';
BEGIN
    if(P_ROLE = 'ROLE_ADMIN') then
        V_USER:='admin';
    end if;
  --DELETE FROM tbl_member WHERE 1 = 1;
  --실행방법: call proc_member_insert(50,'ROLE_ADMIN');
FOR i IN 1..P_COUNT LOOP
        INSERT INTO TBL_MEMBER
        (user_id,user_pw,user_name,enabled,levels,reg_date,update_date)
        VALUES
        (concat(concat(V_USER,'_'),i) ,'$2a$10$kIqR/PTloYan/MRNiEsy6uYO6OCHVmAKR4kflVKQkJ345nqTiuGeO'
        ,'관리자',1,P_ROLE,sysdate,sysdate);
      END LOOP;
    commit;
END PROC_MEMBER_INSERT;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "XE"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "XE"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'I9XJ372AKOTZ2RU11IRLFIZW1W7OV1';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
--------------------------------------------------------
--  Constraints for Table TBL_ATTACH
--------------------------------------------------------

  ALTER TABLE "XE"."TBL_ATTACH" ADD CONSTRAINT "TBL_ATTACH_PK" PRIMARY KEY ("SAVE_FILE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XE"."TBL_ATTACH" MODIFY ("SAVE_FILE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BOARD
--------------------------------------------------------

  ALTER TABLE "XE"."TBL_BOARD" ADD CONSTRAINT "TBL_BOARD_PK" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XE"."TBL_BOARD" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BOARD_TYPE
--------------------------------------------------------

  ALTER TABLE "XE"."TBL_BOARD_TYPE" ADD CONSTRAINT "TBL_BOARD_TYPE_PK" PRIMARY KEY ("BOARD_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XE"."TBL_BOARD_TYPE" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MEMBER
--------------------------------------------------------

  ALTER TABLE "XE"."TBL_MEMBER" ADD CONSTRAINT "TBL_MEMBER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XE"."TBL_MEMBER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_REPLY
--------------------------------------------------------

  ALTER TABLE "XE"."TBL_REPLY" ADD CONSTRAINT "TBL_REPLY_PK" PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XE"."TBL_REPLY" MODIFY ("RNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_ATTACH
--------------------------------------------------------

  ALTER TABLE "XE"."TBL_ATTACH" ADD CONSTRAINT "TBL_ATTACH_TBL_BOARD_FK" FOREIGN KEY ("BNO")
	  REFERENCES "XE"."TBL_BOARD" ("BNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_REPLY
--------------------------------------------------------

  ALTER TABLE "XE"."TBL_REPLY" ADD CONSTRAINT "TBL_REPLY_TBL_BOARD_FK" FOREIGN KEY ("BNO")
	  REFERENCES "XE"."TBL_BOARD" ("BNO") ENABLE;
